const S = require('/home/user/workspace/worktrees/fa72-s11a2/test/fixtures/scout/s11/s11-sources');
const { loadNativeRuleSets } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/reconstruct/native/native-rule-registry');
const { parseNativeRuleSet } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/reconstruct/native/native-rules');
const { loadInductionManifests, buildInductionRegistry } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/induction/manifest-registry');
const { parseInductionManifest } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/induction/parse');
const { evaluateCoverage } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/induction/verify');
const { stagedPlatformFacts } = require('/home/user/workspace/worktrees/fa72-s11a2/src/scout/reconciliation/facts.service');
const { randomBytes } = require('crypto');
const { first, second } = S.SOURCES;
const specs = [...S.MAPPERS.values()].map((m) => m.spec);
const rules = [...loadNativeRuleSets(), ...S.INDUCTION_INPUT.rules.map((r) => parseNativeRuleSet(r, 'x'))];
const manifests = [...loadInductionManifests(), ...S.INDUCTION_INPUT.manifests.map((m) => parseInductionManifest(m, 'x'))];
const registry = buildInductionRegistry({ manifests, specs, nativeRuleSets: rules });
const challenge = randomBytes(32);
const accepted = new Date(Date.now() - 1000);
const issuedAt = new Date(Date.now() - 500).toISOString();
const received = new Date();
const rows = (src) => src.nativeClean.map((r) => ({ source_platform: src.platform, entity_type: r.token, source_id: r.source_id }));
const staged = stagedPlatformFacts(S.MAPPERS, [...rows(first), ...rows(second)]);
const obs = (src) => S.evidenceSet(src, src.nativeClean, challenge.toString('base64'), issuedAt).map((evidence) => ({ coach_id: 'c', intent_id: 'i', execution_epoch: 1, received_at: received, evidence }));
const run = { coach_id: 'c', intent_id: 'i', execution_epoch: 1, accepted_start_at: accepted };
const j09 = evaluateCoverage({ run, registry, staged, declaration: { challenge, platforms: [S.declarationOf(first), S.declarationOf(second)] }, observations: [...obs(first), ...obs(second)] });
const j10 = evaluateCoverage({ run, registry, staged, declaration: { challenge, platforms: [S.declarationOf(first)] }, observations: [...obs(first)] });
console.log('J09', JSON.stringify(j09));
console.log('J10', JSON.stringify(j10));
console.log('first', first.platform, first.families, first.nativeClean.map(r=>r.token), 'second', second.platform, second.families, second.nativeClean.map(r=>r.token));
console.log('ids', S.idsByFamily(first, first.nativeClean), S.idsByFamily(second, second.nativeClean));
console.log('evidence bytes', JSON.stringify({intent_id:'x', observations:[...obs(first),...obs(second)].map(o=>o.evidence)}).length);
