# RT-NEW-1 v1 -> v2 proof-runner substitution. Environment pins re-recorded (REVIEW_A §5.3 / REVIEW_B §2.2);
# repo-content pins untouched; class-C suggestions CB1/CB2/CB3 (REVIEW_B §2.3) and the expected-test-count
# assertion (REVIEW_A) added. Placeholders __MEASURED_*__ are filled from the RT-NEW-1 receipt (see fill step).
import sys
p=sys.argv[1]; s=open(p).read()
def rep(a,b,count=1):
    global s
    assert s.count(a)==count, (s.count(a), a[:80])
    s=s.replace(a,b)
rep("# S8-F real-PG proof — complete source-only execution binding (drafted under S8F-COMP-1; NOT RUN; NOT GRANTED).\n",
    "# S8-F real-PG proof — complete source-only execution binding v2 (RT-NEW-1, EXEC-1910A060; NOT RUN; NOT GRANTED).\n"
    "# v2 = v1 (execution/64e33dc7/s8f/binding/v1, immutable) with ONLY the environment pins re-recorded for the\n"
    "# 1910a060 runtime (runtime root, standalone clone, lane, lock inode commentary, PG17/psql/node hashes, the genuine\n"
    "# npm-ci node_modules + generated client of this clone) plus the class-C review items: CB1 real psql binary pinned and\n"
    "# major asserted; CB2 generated client provenance (schema blob 2e328bbc -> client) checked and target_kind grepped;\n"
    "# CB3 hooks check kept, hook EVIDENCE for e1ec2fec is the original gate log (see README); expected jest test count\n"
    "# asserted (11, counted from test/rls-g2-s8f.spec.ts, REVIEW_A). Every repo-content pin is byte-identical to v1.\n")
rep("# recovery-reset/proof-s8f-v1, NO OLD side","# 1910a060/runtime/proof-s8f-v2, NO OLD side")
rep("# Usage (later, under the separate single-run PG grant): timeout -k 30 3600 bash .../binding/v1/s8f-pg-proof.sh",
    "# Usage (later, under the separate single-run PG grant after dual review of v2): timeout -k 30 3600 bash .../binding/v2/s8f-pg-proof.sh")
rep("D=/home/user/workspace/tgp-private-evidence/execution/64e33dc7/s8f/binding/v1","D=/home/user/workspace/tgp-private-evidence/execution/64e33dc7/s8f/binding/v2")
rep("RUNTIME_ROOT=/home/user/workspace/execution/64e33dc7/recovery-reset","RUNTIME_ROOT=/home/user/workspace/execution/1910a060/runtime")
rep("W=/home/user/workspace/worktrees/daceddc8-s8f","W=/home/user/workspace/worktrees/1910a060-s8f")
rep("EXPECT_FIXTURE_SHA=88e8b2f3123b425211ba9e05c2add93b21a7fc6f5ed8d2bfbf9fd2018e362f30                                   # sha256 of binding/v1/s8f-fixture.sh (frozen with this file)",
    "EXPECT_FIXTURE_SHA=__MEASURED_FIXTURE_SHA__                                   # sha256 of binding/v2/s8f-fixture.sh (frozen with this file)")
rep("EXPECT_PSQL_SHA=a200e38c89b111d3abdf26927b186fdd423bef3d84f157af0f4b65db6f8e6c94       # readlink -f /usr/bin/psql (18.6)",
    "PSQL=/usr/lib/postgresql/18/bin/psql                                                     # CB1: the real client binary, not the pg_wrapper dispatcher\n"
    "EXPECT_PSQL_SHA=__MEASURED_PSQL_SHA__       # sha256 of $PSQL (postgresql-client-18 18.6-0ubuntu0.26.04.1, 1910a060 host)")
rep("EXPECT_NODE_SHA=a03953a7b16bff002b94d6fb58ada900b68241cbcaee6efc400b20dadd36dddc       # /usr/local/bin/node v20.20.1",
    "EXPECT_NODE_SHA=__MEASURED_NODE_SHA__       # /usr/local/bin/node v20.20.1 (1910a060 host, measured)")
rep("EXPECT_NM_LOCK_SHA=05bc530aa44bfa6df64f0daa8edb66c5181abf4bfbc309bd8da2c8aff37b6a44    # node_modules/.package-lock.json (donor land-s8-c)",
    "EXPECT_NM_LOCK_SHA=__MEASURED_NM_LOCK_SHA__    # node_modules/.package-lock.json (genuine npm ci in this clone, RT-NEW-1)")
rep("EXPECT_NM_CLIENT_SHA=9042e713ba5678c99959a345b7b18a60dfc186b2c7d890b8d9c3ed5c8f4edcc6  # node_modules/.prisma/client/index.d.ts (S7-L schema client)",
    "EXPECT_NM_CLIENT_SHA=__MEASURED_NM_CLIENT_SHA__  # node_modules/.prisma/client/index.d.ts (generated by postinstall from prisma/schema.prisma blob 2e328bbc)")
rep("EXPECT_NM_CLIENT_SCHEMA_SHA=b84392033ab86776533007505c31f57930307a210844067a7407ed20d25abf3e  # node_modules/.prisma/client/schema.prisma",
    "EXPECT_NM_CLIENT_SCHEMA_SHA=__MEASURED_NM_CLIENT_SCHEMA_SHA__  # node_modules/.prisma/client/schema.prisma (same generate)")
rep("EXPECT_POSTGRES_SHA=23cd174849b273064c47d581b55be596be2f5cf0ee5d3e76c0146e2464bf873a",
    "EXPECT_POSTGRES_SHA=__MEASURED_POSTGRES_SHA__   # 1910a060/runtime/pg17/dist/bin/postgres (pg17-fetch receipt)")
rep("EXPECT_INITDB_SHA=b7db9bc2463a4ffbe1e405977512afb50c9846fd3af2b694e315e6d5a270882a","EXPECT_INITDB_SHA=__MEASURED_INITDB_SHA__")
rep("EXPECT_PGCTL_SHA=af53d826845af4679a0aaba2bda319f5e527f3b94f3794c67fa174049c9b9401","EXPECT_PGCTL_SHA=__MEASURED_PGCTL_SHA__")
rep("EXPECT_MIGRATIONS=172 ","EXPECT_SCHEMA_BLOB=2e328bbcab0c902c6adb55dfb5ee172defc5f698                                 # prisma/schema.prisma blob @1c10e2a1 and @e1ec2fec (== sha256 0eb41f9a); CB2 provenance anchor\nEXPECT_TESTS=11                                                                         # it() count in test/rls-g2-s8f.spec.ts @e1ec2fec (REVIEW_A; verified by grep, not assumed)\nEXPECT_MIGRATIONS=172 ")
rep("LANE=$RUNTIME_ROOT/proof-s8f-v1/clusters/s8-f; SOCK=$RUNTIME_ROOT/proof-s8f-v1/run/s8-f","LANE=$RUNTIME_ROOT/proof-s8f-v2/clusters/s8-f; SOCK=$RUNTIME_ROOT/proof-s8f-v2/run/s8-f")
rep("G2_S8F_PSQL=/usr/bin/psql","G2_S8F_PSQL=$PSQL")
rep("# the committed head must have been produced through the tracked lefthook hooks\n",
    "# lefthook hooks must be installed in this clone (npm ci `prepare`); this proves the CURRENT hook state only — the evidence\n# that e1ec2fec itself was produced through the hooks is the original gate log (COMMIT rc=0 hook_lines=8), cited in README (CB3)\n")
rep("# dependency tree: an ISOLATED real copy of the runtime donor (not a symlink, not platform node_modules, not a fresh npm ci)",
    "# dependency tree: the genuine `npm ci` output of RT-NEW-1 inside this clone (real dir, not a symlink, not platform node_modules; lock unchanged)")
rep('[ "$(sha "$W/node_modules/.prisma/client/index.d.ts")" = "$EXPECT_NM_CLIENT_SHA" ] || { log "PRECONDITION_FAIL generated client != donor record (no S8-F generate expected)"; fail 70; }',
    '[ "$(sha "$W/node_modules/.prisma/client/index.d.ts")" = "$EXPECT_NM_CLIENT_SHA" ] || { log "PRECONDITION_FAIL generated client != RT-NEW-1 generate receipt (no S8-F generate expected)"; fail 70; }')
rep('[ "$(sha "$W/node_modules/.prisma/client/schema.prisma")" = "$EXPECT_NM_CLIENT_SCHEMA_SHA" ] || { log "PRECONDITION_FAIL generated client schema != donor record"; fail 70; }',
    '[ "$(sha "$W/node_modules/.prisma/client/schema.prisma")" = "$EXPECT_NM_CLIENT_SCHEMA_SHA" ] || { log "PRECONDITION_FAIL generated client schema != RT-NEW-1 generate receipt"; fail 70; }\n'
    '# CB2: the client must know the S8-B/S8-C objects the readers depend on (same greps the committed bootstrap performs on the catalog)\n'
    'grep -q "model ImportNativeProvenance " "$W/node_modules/.prisma/client/schema.prisma" && grep -q "target_kind" "$W/node_modules/.prisma/client/schema.prisma" \\\n'
    '  && grep -q "ImportNativeProvenance" "$W/node_modules/.prisma/client/index.d.ts" && grep -q "target_kind" "$W/node_modules/.prisma/client/index.d.ts" \\\n'
    '  || { log "PRECONDITION_FAIL generated client lacks ImportNativeProvenance/target_kind"; fail 70; }\n'
    '[ "$(git -C "$W" rev-parse HEAD:prisma/schema.prisma)" = "$EXPECT_SCHEMA_BLOB" ] || { log "PRECONDITION_FAIL prisma/schema.prisma blob != 2e328bbc (client provenance)"; fail 70; }')
rep("# tools: pinned PG 17.6 server binaries in the fresh namespace, the recorded psql 18.6 client and Node 20",
    "# tools: pinned PG 17.6 server binaries in the 1910a060 namespace, the real psql 18.6 client binary (CB1) and Node 20")
rep('[ -x /usr/bin/psql ] && [ "$(sha "$(readlink -f /usr/bin/psql)")" = "$EXPECT_PSQL_SHA" ] || { log "PRECONDITION_FAIL /usr/bin/psql absent or sha256 != pin"; fail 70; }',
    '[ -x "$PSQL" ] && [ "$(sha "$PSQL")" = "$EXPECT_PSQL_SHA" ] || { log "PRECONDITION_FAIL $PSQL absent or sha256 != pin"; fail 70; }\n'
    '"$PSQL" --version | grep -qE "^psql \\(PostgreSQL\\) 18\\." || { log "PRECONDITION_FAIL psql major != 18: $("$PSQL" --version)"; fail 70; }')
rep("psql='$(/usr/bin/psql --version)'", "psql='$(\"$PSQL\" --version)'")
rep('timeout -k 30 15 /usr/bin/psql -X','timeout -k 30 15 "$PSQL" -X')
rep("[ $JRC = 0 ] || fail $JRC\n",
    "[ $JRC = 0 ] || fail $JRC\n"
    "# REVIEW_A: the single run must have executed exactly the expected number of tests, all passed, none skipped\n"
    "grep -qE \"^Tests: +$EXPECT_TESTS passed, $EXPECT_TESTS total\" \"$JLOG\" || { log \"JEST_COUNT_FAIL expected 'Tests: $EXPECT_TESTS passed, $EXPECT_TESTS total' (got: $(grep -E '^Tests:' \"$JLOG\" | head -1))\"; fail 72; }\n"
    "log \"JEST_COUNT_OK tests=$EXPECT_TESTS\"\n")
open(p,'w').write(s)
